### ISSUE TITLE
native Java/Apache support

### ISSUE THREAD

**Issue by grettadarmstrong** [seqcode/pegr#172]
Future support may be available for Java to Excel without requiring the external executable that we currently rely upon.

https://poi.apache.org/components/spreadsheet/ 

HSSF is the POI Project's pure Java implementation of the Excel '97(-2007) file format. XSSF is the POI Project's pure Java implementation of the Excel 2007 OOXML (.xlsx) file format.

HSSF and XSSF provides ways to read spreadsheets create, modify, read and write XLS spreadsheets. They provide:
- low level structures for those with special needs
- an eventmodel api for efficient read-only access
- a full usermodel api for creating, reading and modifying XLS files

For people converting from pure HSSF usermodel, who wish to use the joint SS Usermodel for HSSF and XSSF support, then see the ss usermodel converting guide.

An alternate way of generating a spreadsheet is via the Cocoon serializer (yet you'll still be using HSSF indirectly). With Cocoon you can serialize any XML datasource (which might be a ESQL page outputting in SQL for instance) by simply applying the stylesheet and designating the serializer.

If you're merely **reading spreadsheet data**, then use the eventmodel api in either the org.apache.poi.hssf.eventusermodel package, or the org.apache.poi.xssf.eventusermodel package, depending on your file format.

If you're **modifying spreadsheet data** then use the usermodel api. You can also **generate spreadsheets** this way.

**Comment by WilliamKMLai** [comment]
Try again with Java 11?
