### ISSUE TITLE
Incorrect GUI buttons shown: Guest user as a Guest role for a project *appears* to be able to delete sequencing run

### ISSUE THREAD

**Issue by grettadarmstrong** [seqcode/pegr#215]
I was afraid to try this on Thanos, so I was able to do this on Hestia and see that at the end, I was not able to actually delete any data - which is great. However, I was able to go through the process as if I could.  Presumably it fails at the very end because the 'delete' function is admin-only. 

I am wondering if we can designate certain buttons and feature options throughout the software platform that are not visible at all if they are designated to be admin-only functions. Similar to how the 'Admin' console does not appear at all if the user does not have proper permissions. 

[**_note_**: We might also want to discuss which role and which user *is* able to delete an entire sequencing run. I don't think just *any* admin should be able to do that. ]

### Tested behavior on Thanos. Confirmed on Hestia. 

**A userID in the Guest role group:**
![image](https://user-images.githubusercontent.com/19175816/125130990-ffd60400-e0cf-11eb-8707-a65d266eaf40.png)
 
**And only assigned as a Guest role in a Project:**
![image](https://user-images.githubusercontent.com/19175816/125131100-2f850c00-e0d0-11eb-8670-6d4e9f893232.png)

**Will only be able to log in and view the one project, and _mostly_ has only View permissions. It can view the one assigned project plus the software guide, and that is great, however when you dig into the project and open the samples and sequencing run information...**
![image](https://user-images.githubusercontent.com/19175816/125131338-9f939200-e0d0-11eb-8232-2cfa547fbae3.png)
![image](https://user-images.githubusercontent.com/19175816/125131675-1d579d80-e0d1-11eb-93ea-bf07a615fd83.png)

**IF you go to the links for the Sequencing runs INSIDE the reports, those links appear to allow the Guest user/Guest role for the project to delete the entire run.**
![image](https://user-images.githubusercontent.com/19175816/125131839-6a3b7400-e0d1-11eb-8491-43f5f646cd68.png)
![image](https://user-images.githubusercontent.com/19175816/125131878-7e7f7100-e0d1-11eb-88ae-31b68dcd8d14.png)
![image](https://user-images.githubusercontent.com/19175816/125132182-f77ec880-e0d1-11eb-8a11-93672a0fe6bf.png)

****And then it correctly fails, and outputs an error message which is great. Presumably because the 'delete' function is admin-only. ****

**Comment by dshao** [comment]
only allow admin to delete a sequence run.
