### ISSUE TITLE
decouple 4color plot, sequence motif logos, and composite plots

### ISSUE THREAD

**Issue by AliNemat** [seqcode/pegr#225]
Currently, the existence of 4color plot is required for plotting sequence motifs logos and composite plots. So, if one plot is not showing up it is hard to trace down where the error is coming from. Also pipelines without a 4color plot is not feasible. 
I am suggesting to change the code such that one type of the plot can be independently plotted from the others.
<img width="1812" alt="Screen Shot 2021-08-24 at 9 23 21 AM" src="https://user-images.githubusercontent.com/14810328/130624194-7a039c81-8ce9-45b3-86af-d0fb189b7784.png">

**Comment by WilliamKMLai** [comment]
Also please decrease the whitespace to the right of the motif and increase the size of the composite plot
