### ISSUE TITLE
API capability for downloading runInfoNNN.tar.gz file

### ISSUE THREAD

**Issue by AliNemat** [seqcode/pegr#239]
In order to de-multiplex NGS raw data and run Galaxy workflow, runInfoNNN.tar.gz file is needed from PEGR, where NNN is the run number. 
Currently the file can be downloaded through graphical interface by going to "Sequencing Runs"- > "RUN ID: NNN" -> "Download Run Info Files".
Would you please create an API such that the file can be downloaded through command line with an API call. 
Please note that inclusion of the first line in pegr_run_info.txt file where the address of sequencer is given, is not necessary to be provided.

**Comment by WilliamKMLai** [comment]
Related to #240
