### ISSUE TITLE
Search by user name

### ISSUE THREAD

**Issue by amg246** [seqcode/pegr#251]
Is there a way to search by user name for example amg246 to generate a report with all samples done?
<img width="430" alt="Screen Shot 2022-04-07 at 12 04 21 PM" src="https://user-images.githubusercontent.com/90786143/162247621-885656ad-17da-4477-ab95-46694ff6ed11.png">

**Comment by WilliamKMLai** [comment]
<img width="408" alt="Screen Shot 2022-04-12 at 3 32 56 PM" src="https://user-images.githubusercontent.com/18726510/163039599-17832912-a8f1-4005-89c3-38129cbfe48e.png">

<img width="540" alt="Screen Shot 2022-04-12 at 3 34 18 PM" src="https://user-images.githubusercontent.com/18726510/163039819-24eee039-b88b-4cae-acd2-b47a36f0b550.png">

May be easiest to update the Sample search to allow for user search. 'Send data to'
