### ISSUE TITLE
Allow multiple Sample IDs in the side filter on the "Sample" page

### ISSUE THREAD

**Issue by grettadarmstrong** [seqcode/pegr#253]
Right now if you try to type in multiple sample IDs, similar to how samples can be added elsewhere in the app, it only returns the first one. Is it possible to allow multiple sample numbers to be entered into the side filter field? 

<img width="943" alt="image" src="https://user-images.githubusercontent.com/19175816/163198643-81587bcb-64a8-488e-99d0-243bdb45ffe9.png">

**Comment by WilliamKMLai** [comment]
Please add text to the bottom of the search letting people know how/when to use the wildcard
