### ISSUE TITLE
enable adding sequenced cohorts into projects

### ISSUE THREAD

**Issue by grettadarmstrong** [seqcode/pegr#254]
not sure the best way to do this - currently you can add samples/sample IDs into a project, experiments and replicates from the wet bench can also be added into a project, and cohorts are added if they specify the project name in the queue form upload, however there is not a mechanism to add an already sequenced cohort into an existing project in PEGR.

**Comment by dshao** [comment]
https://github.com/seqcode/pegr/wiki/Re-assign-a-cohort-to-another-project
