### ISSUE TITLE
Add hg19,hg38 as a reference genome choice 

### ISSUE THREAD

**Issue by amg246** [seqcode/pegr#255]
I want to edit the reference genomes in 567 samples from hg19 to hg19,hg38. The drop down menu does not have that as a choice. Can hg19,hg38 be added to the menu?

<img width="2097" alt="Screen Shot 2022-04-14 at 1 58 45 PM" src="https://user-images.githubusercontent.com/90786143/163450022-b79d5663-58f3-4e32-be5a-fc202a96438d.png">

**Comment by grettadarmstrong** [comment]
The short answer is "yes", see screenshot. The longer answer though points back to why this field is in PEGR, it is meant to provide the reference genome URL to be used for mapping in the pipeline. Are you asking if it would be possible to make the pipeline map to both of those reference genomes? Just trying to understand the intent here. And then what would be included as the URL to the reference file? 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/19175816/163459865-7fd1aa2f-ea61-4ec7-bd38-cb1197a5cb52.png">

**Comment by amg246** [comment]
We did this for the Lis lab in run 557. They had human cells spiked into mouse samples. On the Queue sheet I listed it as mm10,hg38. It uploaded and ran against both genomes. Will wants to run Hainings samples I submitted this morning against both hg18 and hg38. When I went in to PEGR to edit the Queue, hg19,hg38 doesn't exist. I don't know what URL would be included to the reference file. Does that clarify what I am looking to do?
________________________________

**Comment by grettadarmstrong** [comment]
Yes! That helps a lot. Thanks for clarifying. I need to convene with Will and Danying before recommending next steps. Short answer though is that we can certainly create those options for annotating the queue submissions.

**Comment by grettadarmstrong** [comment]
In the queue form, it is ok to add the comma-delimited genome builds that need to be run per sample. So you can specify multiple genomes.
