### ISSUE TITLE
New reporting feature

### ISSUE THREAD

**Issue by WilliamKMLai** [seqcode/pegr#259]
Allow for arbitrary addition of composite plots in PEGR reporting structure

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/18726510/181272492-bd271b5c-c54f-49aa-b872-74c0d3154c1b.png">

**Comment by dshao** [comment]
To render the composite charts
1. PEGR receives data from Galaxy where category="output_tagPileup"
2. get motif ID from parameters["input2X__identifier__"], e.g. ID = 2 if parameters["input2X__identifier__"]=MOTIF2.gff
3. get the tabular data from datasets["tabular"].last()
4. render small chart on report: url -> fetch text -> javascript 
5. render enlarged interactive chart in composite.gsp: url -> fetch text -> javascript

**Comment by WilliamKMLai** [comment]
2. get motif ID from parameters["input2X__identifier__"], e.g. ID = 2 if parameters["input2X__identifier__"]=MOTIF2.gff

MOTIF - indicates should stay on MEME analysis tab
COMPOSITE - indicates should receive its own dedicated tab

**Comment by WilliamKMLai** [comment]
Composite plot x-axis label should default to "Distance from MEME motif (bp)" to maintain backwards compatibility, but be overrideable in the JSON payload.

Tab title 'Feature Analysis 1' should be the default title but be overrideable in the JSON payload

**Comment by dshao** [comment]
{..., "input2X__identifier__": "COMPOSITE2.gff","title":"SOME TITLE", xlabel: "SOME LABEL", ...}

**Comment by dshao** [comment]
test:
https://juno.vmhost.psu.edu/pegr/report/show/1236

sql:
update analysis set parameters='{"input2X__identifier__":"\\"COMPOSITE3.gff\\"", "title":"my composite", "xlabel":"my x-label"}' where id = 526448;
