### ISSUE TITLE
Create command-line API for fixing sample metadata

### ISSUE THREAD

**Issue by owlang** [seqcode/pegr#260]
We need a command line option for bulk correction of metadata in PEGR. This is going to be a more granular sample-based correction of metadata. 

Below are some sample information to correct, ordered by importance and selected for diverse types of examples. "Field" is based on the returned JSON for the API that retrieves PEGR sample metadata.
| sampleID | field | old_value | new_value | deleteOldValue |
| --- | --- | --- | --- | --- | 
| 31308 | geneticModification | Spt20-D-tag | Gcn5-Dtag | false |
| 31309 | geneticModification | Gcn5-D-tag | Spt20-Dtag | false |
| 20783 | antibodyCatalog | 61412 | 61411 | false |
| 20792 | antibodyCatalog | 61413 | 61411 | false |
| 20793 | antibodyCatalog | 61414 | 61411 | false |
| 20794 | antibodyCatalog | 61415 | 61411 | false |
| 20795 | antibodyCatalog | 61416 | 61411 | false |
| 21353 | target | PolII | Pol2 | true |
| 26417 | geneticModification | spt3-KO | spt3D | true |
| 18824 | strain | yAB001 | AB001 | true |
| 28961 | antibodyCatalog | B01 | ReeseLab-B01 | true |
| 28305 | antibodyCatalog | Reese Lab | ReeseLab-B01 | true |

For the *true* values in the table, I would like to replace all instances of the old_value and only included a couple PEGR sampleID examples. Maybe a better way to think about the true values is generally they are more about reformatting field values with clearer strings while the false values are about correcting incorrect data.

**Comment by amg246** [comment]
Can a way to upload the information from the Queue sheet Column CH and CI to PEGR DB be created with a hyperlink to the sequencing replicates? This is to identify when a sample has been submitted more than once for sequencing for example to get more tags. This identifies samples that should be treated as one. We will need a mechanism to fix mistakes too. 

Samples from run 578 were resequenced  in run 578
PEGR ID
32492=32697
32493=32698
32494=32699
32502=32700

Can this data be added in the PEGR Replicates region? See attached screen shot
<img width="2006" alt="PEGR Replicates" src="https://user-images.githubusercontent.com/90786143/188976604-76aea1a5-d6b1-4789-959e-ce2ba80cf02d.png">

<img width="219" alt="Queue Form" src="https://user-images.githubusercontent.com/90786143/188977260-883fbd68-488d-415a-8660-3dce65a60c3b.png">

**Comment by dshao** [comment]
Current accepted fields include "geneticModification", "antibodyCatalog", "target" and "strain".
