### ISSUE TITLE
Queue sheet upload 

### ISSUE THREAD

**Issue by amg246** [seqcode/pegr#262]
Can a way to upload the information from the Queue sheet Column CH and CI to PEGR DB be created with a hyperlink to the sequencing replicates? This is to identify when a sample has been submitted more than once for sequencing for example to get more tags. This identifies samples that should be treated as one. We will need a mechanism to fix mistakes too. 

Samples from run 578 were resequenced  in run 584
PEGR ID
32492=32697
32493=32698
32494=32699
32502=32700

Can this data be added in the PEGR Replicates region? See attached screen shot
<img width="2006" alt="PEGR Replicates" src="https://user-images.githubusercontent.com/90786143/188976604-76aea1a5-d6b1-4789-959e-ce2ba80cf02d.png">

<img width="219" alt="Queue Form" src="https://user-images.githubusercontent.com/90786143/188977260-883fbd68-488d-415a-8660-3dce65a60c3b.png">

_Originally posted by @amg246 in https://github.com/seqcode/pegr/issues/260#issuecomment-1239872305_

**Comment by dshao** [comment]
1. clean up sample.note
2. import from q-form
3. display
4. export q-form
5. CRUD in admin dashboard
