### ISSUE TITLE
Clicking replicate Set 1 in project gives an error

### ISSUE THREAD

**Issue by jcha40** [seqcode/pegr#263]
I added 4 replicates to technical replicates, but when I click the set, it leads me to an error page.

**Comment by WilliamKMLai** [comment]
@jcha40 Please provide screenshots of the issue

**Comment by jcha40** [comment]
This is what it looks like on the project page:
<img width="2244" alt="image" src="https://user-images.githubusercontent.com/43419629/202253658-ebafc253-5df8-493f-9c18-ba544eeb362d.png">

This is what it I submitted:
<img width="2244" alt="image" src="https://user-images.githubusercontent.com/43419629/202253995-0979e080-f1f6-4e2d-af67-0af02ac0056f.png">

This is the page when I click one of the sets:
<img width="2244" alt="image" src="https://user-images.githubusercontent.com/43419629/202254104-7713da0d-1151-44a0-b99e-6843aa11dfc5.png">

**Comment by WilliamKMLai** [comment]
@dshao 
Project here:
https://thanos.vmhost.psu.edu/pegr/project/show/1252

**Comment by dshao** [comment]
@jcha40 In the latest release of PEGR, the replicates are tired to samples, not projects any more. Please go to the sample's page, e.g. https://thanos.vmhost.psu.edu/pegr/sample/show/32697, to see the replicates you added.

**Comment by dshao** [comment]
@WilliamKMLai  The button on the project page is deprecated in the latest version
