### ISSUE TITLE
Add sample statistics to Project pages

### ISSUE THREAD

**Issue by owlang** [seqcode/pegr#274]
Add a tab with sequencing depth information to the project pages along with a simple sample count at the top. Example shown is based on https://thanos.vmhost.psu.edu/pegr/project/show/1251.
<img width="400" alt="Project_TabbedMetadata" src="https://user-images.githubusercontent.com/15853523/220698569-f230d220-ce5d-433e-81bb-eefcce7cc187.png"><img width="400" alt="Project_SampleStatistics" src="https://user-images.githubusercontent.com/15853523/220698572-de7b2d0e-1987-4a20-be8b-b30dd3a74b48.png">

**Comment by dshao** [comment]
This requires data from the sequence_alignment table will involves too much work. Table for now.
