### ISSUE TITLE
Barcode upload issue

### ISSUE THREAD

**Issue by WilliamKMLai** [seqcode/pegr#277]
When uploading barcodes using upload form, it does not check if the barcode already exists (IndexID key should be unique)

Also no way to delete/archive existing barcodes if an erroneous upload occurs

<img width="588" alt="image" src="https://user-images.githubusercontent.com/18726510/230941267-dc3e9b0b-3f2d-4740-af08-200fe813d041.png">

**Comment by dshao** [comment]
fixed
