### ISSUE TITLE
Export Samples from Search to CSV

### ISSUE THREAD

**Issue by owlang** [seqcode/pegr#288]
Add "Export Samples to CSV" option to "View Samples" page after searching an selecting samples. The first column of the output should be PEGR id and then maybe the rest of the data in the first table can be included in the CSV (I mostly care about the PEGR id).

Output filename: `SampleSearch_<Datetime>.txt`
Output file: `SampleID,Target,Antibody,Strain,Mutation,GrowthMedia,Treatments,Assay,Note`

<img width="1014" alt="1_ExportSearchSamples" src="https://github.com/seqcode/pegr/assets/15853523/2a6de438-990f-426f-ad5e-63736358f4fc">

**Comment by WilliamKMLai** [comment]
Two buttons:
- 'Export Sample Metadata', export every table as CSV. No figures (for now)
- 'Generate PDF report' (skip gel images for now), mimics functionality from report PDF generation

Each row is an alignment.
