### ISSUE TITLE
Make insert size histogram more prominent

### ISSUE THREAD

**Issue by jcha40** [seqcode/pegr#294]
Currently, the insert size histogram is a link in the "Additional Information" tab of the "Mapping Statistics" section:
<img width="1437" alt="image" src="https://github.com/seqcode/pegr/assets/43419629/ad4a8f76-55d7-4773-b360-927dbb186c98">

We likely want to move all the information in the "Additional Information" tab out into its own section since the insert size statistics are a much more important QC tool than they previously were.

**Comment by jcha40** [comment]
The section should be called "Paired-end statistics" and the columns we want in the new table are Sample ID, Sequence Run, Genome, Average Insertion Size, Insert size histogram (with image embedded, new payload)

**Comment by jcha40** [comment]
We probably also want to keep Adapter Dimer Count, so something like this:
<img width="1203" alt="image" src="https://github.com/seqcode/pegr/assets/43419629/bb186eeb-f6e9-4427-acaa-64850a4f0b44">

**Comment by dshao** [comment]
code commit b17228b8 and run the database update:

> update sequence_alignment s inner join (select alignment_id, datasets from analysis where category = 'output_peHistogram') a on s.id = a.alignment_id set s.pe_histogram = JSON_EXTRACT(a.datasets,'$[1].uri')

**Comment by jcha40** [comment]
This has been implemented
