### ISSUE TITLE
Add column in on Sample page for BigWig file downloads

### ISSUE THREAD

**Issue by owlang** [seqcode/pegr#298]
We want two new files to be available for download by the users in a new column under "Files".
<img width="1525" alt="BigWigAddIssueTicket" src="https://github.com/seqcode/pegr/assets/15853523/06ecf70b-b806-4b01-b44c-5abc2e86ac9c">

Output is similar to FASTQ1 and FASTQ2 but with `stats_tool_id="bigwig_dataset_forward_output_stats"` or `stats_tool_id="bigwig_dataset_reverse_output_stats"` and `tool_id="scidx_to_bigwig_forward"` or `tool_id="scidx_to_bigwig_reverse"`.

**Comment by dshao** [comment]
@owlang Expected payload from Galaxy:

{
  "run": 1,
  "sample": 1,
  "genome": "sacCer3_cegr",
  "workflowId": "b266c9aed69b2935",
  "historyId": "58d3202e3",
  "history_url": "https://somepath/hisotry?id=58d3202e3",
  "toolCategory": "output_bigwigForward",
  "statsToolId": "bigwig_dataset_forward_output_stats",
  "workflowStepId": "10a140b06",
  "userEmail": "xxxx@psu.edu",
  "toolId": "scidx_to_bigwig_forward",
  "datasets": [
    {
      "type": "bigwig",
      "id": "e4f3485fe716bd91",
      "uri": "someuri"
    }
  ]
}
