### ISSUE TITLE
PEGR api does not work with OpenSSL

### ISSUE THREAD

**Issue by jcha40** [seqcode/pegr#310]
The PEGR api does not work with OpenSSL. LibreSSL works fine.

**Comment by jcha40** [comment]
Output from running `curl -X POST -H "Content-Type: application/json" -d '{"id": 11690, "userEmail": "jsc6015@psu.edu"}' https://vesta.cac.cornell.edu/pegr/api/fetchSampleData?apiKey=XXXXXX -o pegr_api_test.json` on my local environment with LibreSSL: [pegr_api_test.json](https://github.com/seqcode/pegr/files/14130412/pegr_api_test.json)

Stacktrace for running the same command on a conda environment with OpenSSL:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by jcha40** [comment]
Likely this is due to the transition to Vesta and Cornell's security settings

**Comment by dshao** [comment]
Recreated SSL certificate.
