### ISSUE TITLE
Dynamically change strand of composite plot to match weblogo

### ISSUE THREAD

**Issue by WilliamKMLai** [seqcode/pegr#323]
<img width="1973" alt="image" src="https://github.com/user-attachments/assets/bb8cad16-44fa-469c-9e2a-49ed57383f65">

When the '-' strand is selected, reverse sort the x-axis and change label and colors between R1 forward and R2 reverse

**Comment by WilliamKMLai** [comment]
<img width="1977" alt="image" src="https://github.com/user-attachments/assets/099ce28b-e0ef-4e19-abca-19d7b73caf07">

**Comment by dshao** [comment]
e.g. color and legend for the first array will change from (blue, R1 Forward) to (red, R1 Reverse).
