### ISSUE TITLE
Download change based on Galaxy file extensions

### ISSUE THREAD

**Issue by WilliamKMLai** [seqcode/pegr#332]
Galaxy handles streaming non-BAM files differently and we'll need to modify the stored URLs

1. fastq files should be stream-edited from:
```https://hyperion.cac.cornell.edu/datasets/XXXXXX/display?preview=False```
to
```https://hyperion.cac.cornell.edu/datasets/XXXXXX/display?to_ext=fastqsanger.gz```

2. FASTQ output should be modified from *.fastq to *.fastq.gz

3. bigWig files should be stream-edited from:
```https://hyperion.cac.cornell.edu/datasets/XXXXXX/display?preview=False```
to
```https://hyperion.cac.cornell.edu/datasets/XXXXXX/display?to_ext=bigwig```

**Comment by dshao** [comment]
This is hard-coded for now. It might not be needed in the future when the urls received by PEGR are already in the correct format.
